### ISSUE TITLE
Please add the new "Supplementary" flag (2048).

### ISSUE THREAD

**Issue by w9** [ingolia/SamTools#5]
In the new [SAM format](https://samtools.github.io/hts-specs/SAMv1.pdf), there's a new flag called "Supplementary (2048 = 0x800)", which is used by several alignment softwares. For example, [BWA](http://bio-bwa.sourceforge.net/) uses it to mark the shorter fragments of the read that are mapped elsewhere. There seems to be no way to extact this flag in the current API of your package.

**Comment by ingolia** [comment]
This flag isn't included in the rather old (0.1.18) release of samtools used by this package.

There have been substantial changes to the samtools package, including the refactoring of the htslib away from the command-line tools. Pulling in all of these changes is substantial work, but I will try to address this soon.

I'd certainly consider a pull request for a quick-and-dirty solution to your specific problem if you have one.

**Comment by w9** [comment]
I submitted a pull request.

**Comment by ingolia** [comment]
Your pull request for the Supplementary flag is now available in 0.2.4.2
